#!/usr/bin/env bash
set -euo pipefail

export TORCHINDUCTOR_HYBRID_MM_AXIS="${TORCHINDUCTOR_HYBRID_MM_AXIS:-n}"
export TORCHINDUCTOR_HYBRID_MM_CPU_RATIO="${TORCHINDUCTOR_HYBRID_MM_CPU_RATIO:-0.5}"
export TORCHINDUCTOR_HYBRID_MM_CPU_N_ALIGN="${TORCHINDUCTOR_HYBRID_MM_CPU_N_ALIGN:-32}"
export TORCHINDUCTOR_HYBRID_MM_MIN_CHUNK_N="${TORCHINDUCTOR_HYBRID_MM_MIN_CHUNK_N:-32}"
export TORCHINDUCTOR_HYBRID_MM_MIN_M="${TORCHINDUCTOR_HYBRID_MM_MIN_M:-1}"
export TORCHINDUCTOR_HYBRID_MM_MIN_N="${TORCHINDUCTOR_HYBRID_MM_MIN_N:-64}"
export TORCHINDUCTOR_HYBRID_MM_MIN_K="${TORCHINDUCTOR_HYBRID_MM_MIN_K:-64}"
export TORCHINDUCTOR_FORCE_TRITON_SHARED_MM="${TORCHINDUCTOR_FORCE_TRITON_SHARED_MM:-1}"
export TRITON_SHARED_ENABLE_AMX="${TRITON_SHARED_ENABLE_AMX:-0}"

python3 test_hybrid_mm_eager_bridge_fallback.py
python3 test_hybrid_mm_eager_bridge_backend.py
